const CardData = [
  {
    sellerId: "W001",
    img: "https://images.pexels.com/photos/53588/tomatoes-vegetables-food-frisch-53588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Ton of Tomatoes",
    description: `I got 1 ton of tomatoes to trade, I'm in the dragon's Den area Would love to trade it for some bananas HMU!`,
    location: "Homietown",
    startDate: "22-11-2022 10:01",
    expiryCount: 4,
    expiryFactor: "days",
  },
  {
    sellerId: "W002",
    img: "https://images.pexels.com/photos/691166/pexels-photo-691166.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Orange Oranges",
    description: `Oranges for days come and get em now!`,
    location: "Greenhills",
    startDate: "22-11-2022 10:02",
    expiryCount: 9,
    expiryFactor: "days",
  },
  {
    sellerId: "W005",
    img: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Appealing Apples",
    description: `I got some delicious apples no strings attached, you need to try them`,
    location: "Purplewell",
    startDate: "22-11-2022 10:03",
    expiryCount: 10,
    expiryFactor: "days",
  },
  {
    sellerId: "W005",
    img: "https://images.pexels.com/photos/3568039/pexels-photo-3568039.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Combersome Cucumbers",
    description: `Why didn't I just do a cheeky little Lorem15 here? idk I guess I'm going crazy typing all this myself`,
    location: "Purplewell",
    startDate: "22-11-2022 10:04",
    expiryCount: 2,
    expiryFactor: "days",
  },
  {
    sellerId: "W008",
    img: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Corny Corn",
    description: `Corn Corn Corn Corn Corn Corn Corn Corn Corn CornCorn Corn Corn Corn Corn Corn Corn Corn I like corn`,
    location: "flacidtown",
    startDate: "22-11-2022 10:05",
    expiryCount: 8,
    expiryFactor: "days",
  },
  {
    sellerId: "W009",
    img: "https://images.pexels.com/photos/7657242/pexels-photo-7657242.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Great Grapes",
    description: `Need some grapes? I got em hit me up as soon as you got this`,
    location: "RoflCity",
    startDate: "22-11-2022 10:06",
    expiryCount: 2,
    expiryFactor: "months",
  },
];
export default CardData;
