const CardData = [
  {
    id: 1,
    sellerId: "W001",
    startDate: "22-11-2022 10:00",
    img: "https://images.pexels.com/photos/53588/tomatoes-vegetables-food-frisch-53588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Ton of Tomatoes",
    description: `I got 1 ton of tomatoes to trade, I'm in the dragon's Den area Would love to trade it for some bananas HMU!`,
    location: "Homietown",
    expiry: "sometime",
    expiryCount: 4,
    expiryFactor: "days",
    type: "vegetable",
  },
  {
    id: 2,
    sellerId: "W002",
    startDate: "22-11-2022 10:01",
    img: "https://images.pexels.com/photos/691166/pexels-photo-691166.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Orange Oranges",
    description: `Oranges for days come and get em now!`,
    location: "Greenhills",
    expiry: "sometime",
    expiryCount: 4,
    expiryFactor: "days",
    type: "fruit",
  },
  {
    id: 3,
    startDate: "22-11-2022 10:02",
    sellerId: "W005",
    img: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Appealing Apples",
    description: `I got some delicious apples no strings attached, you need to try them`,
    location: "Purplewell",
    expiry: "10 days",
    expiryCount: 9,
    expiryFactor: "days",
    type: "fruit",
  },
  {
    id: 4,
    sellerId: "w003",
    img: "https://images.pexels.com/photos/3568039/pexels-photo-3568039.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Combersome Cucumbers",
    description: `Why didn't I just do a cheeky little Lorem15 here? idk I guess I'm going crazy typing all this myself`,
    location: "Stony mountains",
    expiry: "2 days",
    type: "vegetable",
    startDate: "22-11-2022 10:03",
    expiryCount: 10,
    expiryFactor: "days",
  },
  {
    id: 5,
    sellerId: "W005",
    img: "https://images.pexels.com/photos/3568039/pexels-photo-3568039.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Combersome Cucumbers",
    description: `Why didn't I just do a cheeky little Lorem15 here? idk I guess I'm going crazy typing all this myself`,
    location: "Purplewell",
    startDate: "22-11-2022 10:04",
    expiry: "once upon a thyme",
    expiryCount: 2,
    expiryFactor: "days",
    type: "fruit",
  },
  {
    id: 6,
    sellerId: "W008",
    startDate: "22-11-2022 10:05",
    img: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Corny Corn",
    description: `Corn Corn Corn Corn Corn Corn Corn Corn Corn CornCorn Corn Corn Corn Corn Corn Corn Corn I like corn`,
    location: "flacidtown",
    expiry: "8 weeks",
    expiryCount: 8,
    expiryFactor: "days",
    type: "vegetable",
  },
  {
    id: 7,
    sellerId: "W009",
    img: "https://images.pexels.com/photos/7657242/pexels-photo-7657242.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Great Grapes",
    description: `Need some grapes? I got em hit me up as soon as you got this`,
    location: "RoflCity",
    expiry: "2 months",
    type: "fruit",
    startDate: "22-11-2022 10:06",
    expiryCount: 2,
    expiryFactor: "months",
  },
  {
    id: 8,
    sellerId: "W010",
    img: "https://images.pexels.com/photos/61127/pexels-photo-61127.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Big Banana",
    description: `I just shoplifted a bunch of bananas not proud of it but hey at least I got some shit to trade now`,
    location: "bigDtown",
    expiry: "2 months",
    startDate: "22-11-2022 10:06",
    expiryCount: 2,
    expiryFactor: "months",
    type: "fruit",
  },
  {
    id: 9,
    sellerId: "W011",
    img: "https://images.pexels.com/photos/434259/pexels-photo-434259.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Ice Ice Baby",
    description: `it's cold af I don't want it nomore trading for water or simmilar`,
    location: "waterridge",
    expiry: "1 hour",
    startDate: "22-11-2022 10:06",
    expiryCount: 2,
    expiryFactor: "months",
    type: "other",
  },
  {
    id: 10,
    sellerId: "W012",
    img: "https://images.pexels.com/photos/6697339/pexels-photo-6697339.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Semi clean gummybears",
    description: `Found these gummy bears on the traill. Got stomach ate half way through them, trading the rest for some Toilet paper`,
    location: "Spacetown",
    expiry: "idk",
    startDate: "22-11-2022 10:06",
    expiryCount: 2,
    expiryFactor: "months",
    type: "other",
  },
  {
    id: 11,
    sellerId: "W001",
    startDate: "22-11-2022 10:11",
    img: "https://images.pexels.com/photos/2286776/pexels-photo-2286776.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "POTATO",
    description: `POTATO`,
    location: "POTATOland",
    expiry: "Potato",
    expiryCount: 4,
    expiryFactor: "days",
    type: "vegetable",
  },
];
export default CardData;
